# Generated by Django 3.0.8 on 2020-08-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yomdemo', '0003_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slide',
            new_name='slides',
        ),
    ]
