# Generated by Django 3.0.8 on 2020-08-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yomdemo', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.CharField(default='block', max_length=50),
        ),
        migrations.AddField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='yomdemo.User'),
            preserve_default=False,
        ),
    ]
