# Generated by Django 3.0.8 on 2020-08-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yomdemo', '0008_auto_20200807_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
